### DISCUSSION TITLE
关于你页面贪吃蛇问题

### DISCUSSION THREAD

**Discussion by yuluoqingcheng** [sun0225SUN/sun0225SUN#13] [Q&A] [answered]
# 问题描述
我在Github 操作里面新增了自动化文件（yml） 但是生成出来的文件只有一条蛇 没有其他东西了 他也不动
## 我使用的脚本内容
```yml
# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Contribution Snake'
```

## 目前生成的文件
她不运动 只能这样 不知道为什么
![生成的贪吃蛇文件]( https://raw.githubusercontent.com/yuluoqingcheng/yuluoqingcheng/main/assets/github-contribution-grid-snake.svg "这是yml生成的 他不运动")

@sun0225SUN  期待你的回复
