### ISSUE TITLE
关于 我在仓库新增贪吃蛇问题

### ISSUE THREAD

**Issue by yuluoqingcheng** [sun0225SUN/sun0225SUN#14]
# 问题描述
我在Github 操作里面新增了自动化文件（yml） 但是生成出来的文件只有一条蛇 没有其他东西了 他也不动
## 我使用的脚本内容
```yml
# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Contribution Snake'
```

## 目前生成的文件
她不运动 只能这样 不知道为什么
![生成的贪吃蛇文件]( https://raw.githubusercontent.com/yuluoqingcheng/yuluoqingcheng/main/assets/github-contribution-grid-snake.svg "这是yml生成的 他不运动")

@sun0225SUN  期待你的回复

**Comment by ng-fukgin** [comment]
```
name: Snake Contrib

on:
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/profile-snake-contrib/github-contribution-grid-snake.svg
            dist/profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN : ${{ secrets.ACCESS_TOKEN }}
```

readme.md
```
<div align="center">


<!-- Snake Code Contribution Map 贪吃蛇代码贡献图 -->
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://cdn.jsdelivr.net/gh/你的ID/你的ID/profile-snake-contrib/github-contribution-grid-snake-dark.svg" />
  <source media="(prefers-color-scheme: light)" srcset="https://cdn.jsdelivr.net/gh/你的ID/你的ID/profile-snake-contrib/github-contribution-grid-snake.svg" />
  <img alt="github-snake" src="https://cdn.jsdelivr.net/gh/你的ID/你的ID/profile-snake-contrib/github-contribution-grid-snake-dark.svg" />
</picture>

</div>
```

希望能够帮到你
